In [1]:
import numpy as np
import pandas as pd



In [9]:
# Exercise 1
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# Exercise 2
arr2 = np.arange(1, 21)
subset_arr2 = arr2[5:16]  
print(subset_arr2)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [13]:
# Exercise 3
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [15]:
data = {
    'name': ["Asha", "Bobby", "Charly", "David", "Elsa", "Francis", "Genny", "Helen", "Kevin", "Sunny"],
    'age': [25, 32, 28, 45, 30, 26, 38, 40, 29, 35],
    'gender': ["F", "M", "M", "M", "F", "M", "F", "F", "M", "M"]
}
df = pd.DataFrame(data)
print(df)

      name  age gender
0     Asha   25      F
1    Bobby   32      M
2   Charly   28      M
3    David   45      M
4     Elsa   30      F
5  Francis   26      M
6    Genny   38      F
7    Helen   40      F
8    Kevin   29      M
9    Sunny   35      M


In [17]:
# Exercise 5
df['occupation'] = ["Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]
print(df)

      name  age gender  occupation
0     Asha   25      F  Programmer
1    Bobby   32      M     Manager
2   Charly   28      M     Analyst
3    David   45      M  Programmer
4     Elsa   30      F     Manager
5  Francis   26      M     Analyst
6    Genny   38      F  Programmer
7    Helen   40      F     Manager
8    Kevin   29      M     Analyst
9    Sunny   35      M  Programmer


In [21]:
# Exercise 6
df1 = df[df['age'] >= 30]
print(df1)

    name  age gender  occupation
1  Bobby   32      M     Manager
3  David   45      M  Programmer
4   Elsa   30      F     Manager
6  Genny   38      F  Programmer
7  Helen   40      F     Manager
9  Sunny   35      M  Programmer


In [29]:
# Exercise 7
df.to_csv("data.csv")
df_read = pd.read_csv("data.csv")
print(df_read)


   Unnamed: 0     name  age gender  occupation
0           0     Asha   25      F  Programmer
1           1    Bobby   32      M     Manager
2           2   Charly   28      M     Analyst
3           3    David   45      M  Programmer
4           4     Elsa   30      F     Manager
5           5  Francis   26      M     Analyst
6           6    Genny   38      F  Programmer
7           7    Helen   40      F     Manager
8           8    Kevin   29      M     Analyst
9           9    Sunny   35      M  Programmer
